backend:
  name: git-gateway
  logo_url: https://blogdaquarentena.netlify.app/icons/icon-48x48.png
  site_url: blogdaquarentena.netlify.app
  
media_folder: static/assets/img
public_folder: /assets/img
publish_mode: editorial_workflow

collections:
  - label: Posts do Blog
    name: posts
    folder: Posts
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    create: true
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Descrição", name: "description", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime", format: 'DD-MMMM-YYYY hh:mm:ss'}
      - {label: "Autor", name: "author", widget: "string"}
      - {label: "Thumbnail", name: "image", widget: "image"}
      - {label: "Tags", name: "tags", widget: "list", default: ['']}
      - {label: "Corpo", name: "body", widget: "markdown"}