backend:
  name: git-gateway
  preview_context: netlify/netlify-cms-www/deploy-preview

display_url: https://blogdaquarentena.netlify.app
logo_url: https://blogdaquarentena.netlify.app/icons/icon-192x192.png
site_url: https://blogdaquarentena.netlify.app
  
media_folder: static/assets/img
public_folder: /assets/img
publish_mode: editorial_workflow
locale: 'pt'

collections:
  - label: Posts do Blog
    name: posts
    description: "Crie um novo post para o Blog.\n Com amor McLovin."
    folder: Posts
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    preview_path: /{{title}}
    create: true
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Descrição", name: "description", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime", format: 'YYYY-MM-DD hh:mm:ss'}
      - {label: "Autor", name: "author", widget: "string"}
      - {label: "Thumbnail", name: "image", widget: "image"}
      - {label: "Tags", name: "tags", widget: "list", default: ['']}
      - {label: "Corpo", name: "body", widget: "markdown"}